- CMakeLists.txt
- Source/GUI/Panels/ValentineCenterPanel.cpp
- Source/GUI/Panels/ValentineCenterPanel.h
- Source/GUI/Panels/ValentineMainPanel.h
- Source/PluginEditor.cpp
- Source/PluginEditor.h
- Source/PluginProcessor.cpp
- Source/PluginProcessor.h
- libs/Common/DSP/EnvelopeDetector.cpp
- libs/Common/GUI/Components/Panels/PresetPanel.cpp
- libs/Common/GUI/Components/Panels/PresetPanel.h
- libs/Common/GUI/Components/Panels/VerticalMeterPanel.cpp
- libs/Common/GUI/Components/Panels/VerticalMeterPanel.h
- libs/Common/GUI/Components/Widgets/FlatTextButton.cpp
- libs/Common/GUI/Components/Widgets/FlatTextButton.h
- libs/Common/GUI/Components/Widgets/FlatTextChooser.cpp
- libs/Common/GUI/Components/Widgets/FlatTextChooser.h
- libs/Common/GUI/Components/Widgets/LabelSlider.cpp
- libs/Common/GUI/Components/Widgets/LabelSlider.h
- libs/Common/GUI/Components/Widgets/ParameterSlider.h
- libs/Common/GUI/Components/Widgets/ParameterTextButton.cpp
- libs/Common/GUI/Components/Widgets/ParameterTextButton.h
- libs/Common/GUI/LookAndFeel/LookAndFeel.cpp
- libs/Common/GUI/LookAndFeel/LookAndFeel.h
- libs/Common/GUI/LookAndFeel/LookAndFeelConstants.h
- libs/Common/GUI/Managers/RadioButtonGroupManager.cpp
- libs/Common/GUI/Managers/RadioButtonGroupManager.h
- libs/Common/GUI/Utilities/GraphicsUtilities.cpp
- libs/Common/GUI/Utilities/GraphicsUtilities.h
JUCE can't create a header for our test target. That, or it is not 
straightforward to do so. Using this header and simply including
into any file using JUCE functionality is somewhat of an anti pattern 
(only include what you use) and has been made optional as of JUCE's
addition of CMake support.
So let's not create the JUCE header and include what we actually need.
...and namespace anything we use. `using namespace juce` is defined
in no longer created header. And it would be more clear to fully qualify
any uses of those methods.
> Make plugin target build without juce headers

- .github/workflows/cmake_ctest.yml
The originating repo, `apple-actions`, hasn't been updated since October of last year.
In the meanwhile, fixes to issues and deprecations raised in `apple-actions` were merged
not to the main repo, but the `slidoapp` fork.
> Try bumping version to that found in slido fork

- .github/workflows/cmake_ctest.yml
The action we are currently relying on, `apple-actions/import-codesign-certs`
(or, to be specific, our fork of that repo), is in a not great state. 
There are deprecations that have not been fixed, and the tip of master doesn't build (the tagged release does work, however). 
On top of that, I don't feel entirely comfortable handing off secrets to a third party action. Too 
paranoid? Perhaps. 
The changes here also show that the third party solution is a bit over engineered.
Importing certificates is a somewhat straightforward process, so why not do it right
in out action?
Also implemented is post signing cleanup of the temporary key chain used to hold our
signing certificate.
> Handle codesign certificate download without the use of third party actions

- .github/workflows/cmake_ctest.yml
- CMakeLists.txt
- resources/installer_mac/License.txt
- resources/installer_mac/Readme.rtf
- scripts/make-mac-installer.sh
The template from which this project is generated created disk images
with the plugins and symlinks to the user's plugin directories. The user
is meant to install the plugins by dragging them into the symlinks. This
is broken until MacOs Ventura. 
Delivering the plugin as a package installer  avoids this issue with dragging 
into the plugin directories not working. I also think it's  an improved
user experience.
The installer script was adapted from [surge](https://github.com/surge-synthesizer/sst-plugininfra/blob/405191324c905cc0e7415a96f2016ad3aee81042/scripts/installer_mac/make_installer.sh).
> Create macOs package installer in actions

- packaging/installer.iss
This PR addresses issue https://github.com/Tote-Bag-Labs/valentine/issues/11, 
which describes the Windows installer's failure to install Valentine when run.
There were many reasons for this, all coming down to pathing to the source
directory. At first, I had forgotten to change the name from the template project.
This did not fix the issue. This is probably because `recursesubdirs` was not 
specified. But it could also be because of `{src}` being used in the source
directory path.
Other improvements were added, taking liberally from Surge XT's [installer.](https://github.com/surge-synthesizer/surge/blob/main/scripts/installer_win/surge64.iss)
These include installing Valentine to a "Tote Bag Labs" folder along with a 
link to a data folder that can be used for things like factory presets …
> Fix: Windows installer doesn't install the plugin

- src/PluginProcessor.cpp
(probably also fixes FruityLoops too and may fix other hosts with variable block sizes)
> Fix the juce BlockSize API so plugin works in Logic

- src/PluginProcessor.cpp
- src/PluginProcessor.h
Valentine's compressor threshold is linked to the ratio setting.
Generally, raising the ratio raises the threshold. Valentine's threshold
setting is also affected by `nice` mode. Setting `nice` to `on` applies
an offset to the threshold, effectively raising it for all ratios.
Or at least it should. Inspection of the parameter change handling
revealed that changing the compression ratio after `nice` has been
set to on caused the threshold to be set without the offset, effectively
disabling `nice` mode despite the parameter being enabled.
This was fixed by keeping track of whether `nice` is enabled and 
using that to apply the offset whenever ratio, and hence threshold,
change.
Some other fixes were applied—the variable used to keep track of nice
mode enablement was originally used in the …
> Fix nice mode

- scripts/installer_win/installer.iss
Deleted a setup option that wasn't doing anything
Added a check for 64-bit architecture. This should
cause the installer to fail if user tries to install it on a non
64bit system.
> Cleanup some missed setup in windows installer

- scripts/installer_win/installer.iss
After fixing the Windows installer, I submitted a pull
request to `pamplejuce`. In doing so, I found some things
I thought could be better. These changes are the result.
The biggest change is new directory structure for the data
directory. This was done in order to stop uninstall from
causing an error due to file explorer being in a now deleted
directory. 
Moving the symlink outside of the main install directory and
deleting it on uninstall results in error-free operation.
Should probably keep an eye on this, as I must admit that
I don't totally understand why this fix works. I'm confident, though
that a miss here will not cause harm.
Release Notes
--------------
Current users should be advised to delete their installations 
manually before installing the next release that contains these …
> Windows installer cleanups

- .gitignore
I'm working on building valentine using vscode, using lldb for debugging.
The defaults for building from cmake using vscode's cmake tools extension
creates a `Build` folder. This is a spelling choice one might generally make when
configuring, so I thought it best to add to `.gitignore`.
lldb creates a `.cache` file, which we also do not want to check in.
> Add build and .cache to .gitignore

- libs/tote_bag/dsp/ThiranAllpass.h
- src/PluginProcessor.cpp
- src/PluginProcessor.h
These changes improve Valentine's sound my more correctly
aligning processed and unprocessed signal in the audio processor.
They also greatly simplify the allpass interpolator used for this
alignment.
The underlying issues were found when attempting to 
resolve compiler warnings in `ThiranAllpass.h`. Upon examination,
I realized that the implementation wasn't really doing what I 
thought it was.
Instead of creating filter coefficients for a given delay amount, 
errors in my implementation lead to the same coefficients being 
set regardless of what has been set.
This is because `N`, the filter order, was being cast to `int`, 
making it `0` for values less than `1`. This leads to _problems_
when calculating the filter's coefficients, as the filter's order is 
needed.
Furthermore, I didn't …
> Spruce up thiran

- .github/workflows/cmake_ctest.yml
- CMakeLists.txt
- src/PluginProcessor.cpp
- src/PluginProcessor.h
1. Don't create a message manager in the DSP thread
2. Set validation level to 1 for linux since the leak of a Glyph (run the standalone and quit to see it) holds a timer in UI tests it seems
3. Add the Standalone to the CMake
> Linux Validation Support

- libs/tote_bag/juce_gui/components/panels/VerticalMeterPanel.cpp
- libs/tote_bag/juce_gui/components/panels/VerticalMeterPanel.h
- src/gui/panels/ValentineMainPanel.cpp
- src/gui/panels/ValentineMainPanel.h
Just get it from the component hierarchy—it's more clear 
this way. We generally depend on parent look and feel to sort 
out that of a given component. This pattern was broken 
here because of the desire to set some extra colours in the level
meters constructor. 
Better: override `lookAndFeelChanged` and, when it is called, get the 
parent look and feel, make the changes we need, and pass it into the 
meter components that need it.
> Don't create a new look and feel object for meters

- .github/workflows/cmake_ctest.yml
We need this to release linux, of course.
> Enable upload of linux artifacts in workflow [ci skip]

- .github/workflows/cmake_ctest.yml
- CMakeLists.txt
- libs/tote_bag/juce_gui/lookandfeel/LookAndFeel.cpp
- libs/tote_bag/juce_gui/lookandfeel/LookAndFeel.h
- libs/tote_bag/juce_gui/utilities/tbl_font.cpp
- libs/tote_bag/juce_gui/utilities/tbl_font.h
Finally building and running in linux revealed an issue—memory leaks associated
with the custom font. This is likely because the font was being created with 
`static` lifetime duration.
The implementation had other issues—we were getting our custom font by
setting a new default typeface, which required setting our look and feel as 
the default on instantiation. This makes it hard to reason about the lifetime
of our look and feel, especially when several instances of the plugin are open
at once.
Not only that, the standing implementation restricted us to the use of one font
for all of our components. What if we want a different font or different styling?
To resolve these issues, a font holding class was introduced. It can create and
store an arbitrary number of custom fonts in a resource …
> Improve custom font handling

- libs/tote_bag/dsp/DigiDegraders.cpp
- libs/tote_bag/dsp/DigiDegraders.h
- src/PluginProcessor.cpp
I had bit crush on my mind, so I took a look at our bitcrush
implementation for the first time in a while. There were problems!
Valentine uses a simple method for bit crushing a signal:
`quotient = 1 / 2 ^ bits`
`output = quotient * floor(input / quotient)`
I implemented this under the assumption that `bits` needed to be an integer,
so I did some wacky stuff in order to allow for a continuous control range.
These changes dispense with that, making for a more readable and slightly more
efficient implementation. 
The work made me reflect a bit more on what this effect was doing as well.
the actual equation for uniform quantization is:
`output = quotient * floor((input / quotient) +.5)`
This correctly rounds input samples to the nearest quantization step.
What happens if we don't add the …
> Spruce up crush

- .clang-format
- CMakeLists.txt
- libs/tote_bag/dsp/AudioHelpers.h
- libs/tote_bag/dsp/Saturation.cpp
- libs/tote_bag/dsp/Saturation.h
- libs/tote_bag/utils/type_helpers.hpp
- src/PluginProcessor.cpp
- tests/AudioHelpersTests.cpp
And so continues our crusade against warnings.
In this case, most of our warnings were implicit `float` to `double`
conversion. These were mainly resolved by amending our function interfaces to accept `float`. 
One exception is the `hyperTanFirstAntiDeriv`. This function has been
the source of overflows for a while now. Earlier I figured that the `cosh`
call was the culprit, as that function blows up for silly large numbers.
Because of this, I implemented a wrapper function that first clips input
that would cause an overflow.
One thing I neglected to consider is that the range to which input is clipped
is determined by the type in use. Originally, this was all implemented using
`double`. These changes, however, changed everything to `float`, as that is
the type we expect from calling code …
> Resolve implicit conversion warnings in saturator

- libs/tote_bag/dsp/AudioHelpers.h
- libs/tote_bag/dsp/Saturation.cpp
- libs/tote_bag/dsp/Saturation.h
As described in the attached issue, turning `Saturation` up worked as intended,
but _also_ made the output quieter. This is because of the way gain was being 
normalized. This is because of the overly simplistic normalization used in saturation
processing. 
Here's how we were doing it:
`y = f(x * gain) / gain`
This works in that it keeps the signal from getting too loud and hence requiring manual
gain adjustment when turning up `Saturation`. This doesn't actually work because the 
the function is, of course, nonlinear. The function's output won't increase as much as
gain does. Dividing the output of this function by `gain`, then, will make the output 
quieter.
What we need is for the gain compensation to ease up for larger `gain` inputs. 
The following works a lot better:
`y = f(x * gain) …
> Fix saturation gain scaling

- libs/tote_bag/dsp/Saturation.cpp
- libs/tote_bag/dsp/Saturation.h
- src/PluginProcessor.cpp
- src/ValentineParameters.h
These changes aim to make our interpolated clippers sound a little
bit better. This is accomplished, in general, by lowering the tolerance
for when we decide to use the non-interpolated version to prevent a 
divide by zero.
My reasoning here is not rigorous: I figure that, as the conventional
calculation is only there for when the system get into a bad state otherwise,
we should use the interpolated version as much as possible.
This led me to replace the hand rolled calculation of the interpolated
hyperbolic sine with the standard library implementation. For whatever
reason, it sounded better when lowering the tolerance point than
the calculation I had been using. Either way, I had to choose a tolerance
a bit higher than what I thought would be necessary—a sign that I'm
doing something …
> Saturation cleanups

- libs/tote_bag/utils/tbl_math.hpp
- src/PluginProcessor.cpp
- tests/MathTests.cpp
I thought of better names while writing about the changes that introduced
`piecewiseLinearInterpolate`. Now it's called `piecewiseRemap`.
> Rename piecewiseLinearInterpolate to piecewiseRemap

- src/PluginProcessor.cpp
These changes lower the gain going into Valentine's final
clipping section. This makes gain matching a little trickier for
loud input (overs are more likely), but it allows for a cleaner, more
dynamic sound. The tools are still there to make it totally nasty, if needed.
I also added some constants to quickly try different gain settings at the 
output clipper stage. By release, these should be removed.
> Tweak Output Clip

- src/PluginProcessor.cpp
- src/ValentineParameters.h
These changes introduce constants for bit crush min/max values,
and correctly initializes the bitcrusher to 16 bits when Valentine starts.
> 59 correctly initialize bits

- src/PluginProcessor.cpp
- https://github.com/tote-bag-labs/valentine/pull/67
resulted in bit crush values to be incorrectly mapped during parameter changes
(I reversed them, lol). These changes fix this.
> Fix param setting for crush

- README.md
- libs/tote_bag/dsp/Saturation.cpp
- libs/tote_bag/dsp/Saturation.h
- libs/tote_bag/juce_gui/components/widgets/FlatTextButton.cpp
- src/PluginProcessor.cpp
- src/PluginProcessor.h
- src/ValentineParameters.h
- src/gui/panels/ValentineCenterPanel.cpp
- src/gui/panels/ValentineCenterPanel.h
Using Valentine on full mixes, as when processing samples,
showed that the distortion was a little too intense for subtle use cases.
Electric keys, for example, would get too edgy. 
So I decided to make the output clip optional: it's mostly there to prevent
overs when compressing wildly. This is less of a risk with already mixed material,
and it's nice to have the choice.
This desire for a little less distortion also led to the minimum for `Saturation` to be
decreased, because even at 0 it was distorting quite a bit when `Ratio` is set very low.
Another new bit: using more JUCE dsp. I wanted to get away from that, but the other 
option was implementing more dsp for non cool use cases (latency compensation). Why?
> Output clip param

- .github/workflows/cmake_ctest.yml
- CMakeLists.txt
I came back from a break only to find things on fire. Nothing was building on CI.
- Windows failed because it now was missing `ninja`, for some reason.
- Linux failed because https://github.com/actions/runner-images/issues/8659
- Mac failed because I had to sign updated terms.
These changes fix the first two issues. The latter is resolved out of band.
> update things to fix ci

- .github/workflows/cmake_ctest.yml
The workaround for building linux introduced [here]
(https://github.com/tote-bag-labs/valentine/pull/96) broke. :(.
Bumping the libc version used in the workaround fixes the issue, 
as described [here](https://github.com/actions/runner-images/issues/8659#issuecomment-1853177960)
> Fix linux ci again

- .github/workflows/cmake_ctest.yml
Updates to `apt-get`'s package list broke the workaround used to keep Linux building.
So let's use the new versions!
> Fix Linux workaround

- src/gui/panels/ValentineBottomRowPanel.cpp
- src/gui/panels/ValentineTopRowPanel.cpp
Somehow I added some spaces, making build fail if`USE_JUCE_LIVE_CONSTANT`
is set to `1` in `cmakelists.txt`.
> Fix formatting for JUCE_LIVE_CONSTANT includes

- libs/tote_bag/juce_gui/components/panels/PresetPanel.cpp
- src/gui/panels/ValentineBottomRowPanel.cpp
- src/gui/panels/ValentineTopRowPanel.cpp
These changes move buttons a little closer to their corresponding
sliders, as well as making them a little larger.
There's also an unrelated cleanup (variable rename)
> Adjust button placement

- src/gui/panels/ValentineBottomRowPanel.cpp
- src/gui/panels/ValentineTopRowPanel.cpp
Making the buttons closer to the sliders caused a bug where the sliders intercepted
clicks meant for the buttons. Not great! Now you can always click the buttons.
> Fix button clicks
